#use_frameworks!

target 'TFVideoPlayer_Example' do
  pod 'TFVideoPlayer', :path => '../'

#  target 'TFVideoPlayer_Tests' do
#    inherit! :search_paths

#  pod 'Specta'
#  pod 'Expecta'
#  pod 'FBSnapshotTestCase'
#  pod 'Expecta+Snapshots'
#  end
end
